// front_end-frameworks/svelte/src/components/ui/LinkList.svelte
<script>
  export let title;
  export let links;
</script>

<div class="justify-left flex flex-col">
  <h3 class="mb-4 text-sm font-bold">{title}</h3>
  <ul class="flex flex-col gap-2 text-xs text-slate-500">
    {#each links as link, i (i)}
      <li>
        <a href={link.link}>{link.text}</a>
      </li>
    {/each}
  </ul>
</div>

// front_end-frameworks/react/src/components/ui/LinkList.jsx
export default function LinkList({ title, links }) {
  return (
    <div className="justify-left flex flex-col">
      <h3 className="mb-4 text-sm font-bold">{title}</h3>
      <ul className="flex flex-col gap-2 text-xs text-slate-500">
        {links.map((link, index) => (
          <li key={index}>
            <a href={link.link}>{link.text}</a>
          </li>
        ))}
      </ul>
    </div>
  );
}
