// front_end-frameworks/vue/src/components/ui/SocialLink.vue
<script setup>
const props = defineProps({
  href: {
    type: String,
    required: true
  },
  label: {
    type: String,
    required: true
  }
});
</script>

<template>
  <a
    :href="href"
    target="_blank"
    rel="noopener noreferrer"
    :aria-label="label"
    class="flex size-8 items-center justify-center rounded-lg border border-slate-800 bg-black transition-colors hover:bg-slate-800"
  >
    <slot></slot>
  </a>
</template>

// front_end-frameworks/react/src/components/ui/SocialLink.jsx
function SocialLink({ href, label, children }) {
    return (
        <a
            href={href}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={label}
            className="flex items-center justify-center size-8 rounded-lg bg-black border border-slate-800 hover:bg-slate-800 transition-colors"
        >
            {children}
        </a>
    );
}

export default SocialLink;
