// front_end-frameworks/svelte/src/components/cards/StatCard.svelte
<script>
  export let stat;
  export let value;
</script>

<div class="flex flex-col-reverse rounded-xl border border-slate-800 bg-slate-950 p-6 shadow-xl shadow-slate-950/40">
  <dt class="text-center text-xs text-slate-500">
    {stat}
  </dt>
  <dd class="text-center text-4xl font-black text-violet-300">
    {value}
  </dd>
</div>

// front_end-frameworks/react/src/components/cards/StatCard.jsx
export default function StatCard({ stat, value }) {
  return (
    <div className="flex flex-col-reverse rounded-xl border border-slate-800 bg-slate-950 p-6 shadow-xl shadow-slate-950/40">
      <dt key={stat} className="text-center text-xs text-slate-500">
        {stat}
      </dt>
      <dd className="text-center text-4xl font-black text-violet-300">
        {value}
      </dd>
    </div>
  );
}
