// front_end-frameworks/vue/src/components/sections/Hero.vue
<script setup>
import CoolBackground from '../ui/CoolBackground.vue';
import SectionBadge from '../ui/SectionBadge.vue';
import SectionTitle from '../ui/SectionTitle.vue';
import Button from '../ui/Button.vue';
import StatCard from '../cards/StatCard.vue';

const stats = [
  { stat: 'Active agents', value: '10K+' },
  { stat: 'Uptime', value: '99.9%' },
  { stat: 'Tasks automated', value: '50M+' },
  { stat: 'Support', value: '24/7' },
];
</script>

<template>
  <section
    id="hero-section"
    class="relative flex flex-col items-center pt-36 pb-24"
  >
    <CoolBackground />

    <div class="mx-auto flex max-w-6xl flex-col items-center gap-8 px-6">
      <SectionBadge>The future of coding</SectionBadge>
      <hgroup class="flex flex-col items-center">
        <SectionTitle
          level="h1"
          type="big"
          text1="Build smarter workflows"
          text2="with Agentic AI"
          className="mb-8"
        />
        <p class="w-8/10 text-center">
          Create autonomous AI agents that think, plan and execute complex
          tasks. Transform your business with intelligent automation.
        </p>
      </hgroup>
      <div class="mt-8 flex flex-col items-center justify-center gap-4 md:flex-row">
        <Button variant="primary">
          Start learning with Holberton School
        </Button>
        <Button variant="secondary">Methodology</Button>
      </div>
      <dl class="mt-8 grid w-full max-w-4xl grid-cols-2 gap-8 md:grid-cols-4">
        <StatCard v-for="stat in stats" :key="stat.stat" :stat="stat.stat" :value="stat.value" />
      </dl>
    </div>
  </section>
</template>

// front_end-frameworks/react/src/components/sections/Hero.jsx
import CoolBackground from "../ui/CoolBackground.jsx";
import SectionBadge from "../ui/SectionBadge.jsx";
import SectionTitle from "../ui/SectionTitle.jsx";
import Button from "../ui/Button.jsx";
import StatCard from "../cards/StatCard.jsx";

const stats = [
  { stat: "Active agents", value: "10K+" },
  { stat: "Uptime", value: "99.9%" },
  { stat: "Tasks automated", value: "50M+" },
  { stat: "Support", value: "24/7" },
];

export default function Hero() {
  return (
    <section
      id="hero-section"
      className="relative flex flex-col items-center pt-36 pb-24"
    >
      <CoolBackground />

      <div className="mx-auto flex max-w-6xl flex-col items-center gap-8 px-6">
        <SectionBadge>The future of coding</SectionBadge>
        <hgroup className="flex flex-col items-center">
          <SectionTitle
            level="h1"
            type="big"
            text1="Build smarter workflows"
            text2="with Agentic AI"
            className="mb-8"
          />
          <p className="w-8/10 text-center">
            Create autonomous AI agents that think, plan and execute complex
            tasks. Transform your business with intelligent automation.
          </p>
        </hgroup>
        <div className="mt-8 flex flex-col items-center justify-center gap-4 md:flex-row">
          <Button variant="primary">
            Start learning with Holberton School
          </Button>
          <Button variant="secondary">Methodology</Button>
        </div>
        <dl className="mt-8 grid w-full max-w-4xl grid-cols-2 gap-8 md:grid-cols-4">
          {stats.map(({ stat, value }) => (
            <StatCard key={stat} stat={stat} value={value} />
          ))}
        </dl>
      </div>
    </section>
  );
}
