// front_end-frameworks/svelte/src/App.svelte
<script>
  import Header from "./components/layout/Header.svelte";
  import Footer from "./components/layout/Footer.svelte";
  import Hero from "./components/sections/Hero.svelte";
  import About from "./components/sections/About.svelte";
  import Features from "./components/sections/Features.svelte";
  import Insights from "./components/sections/Insights.svelte";
  import Contact from "./components/sections/Contact.svelte";
</script>

<div class="flex min-h-screen flex-col">
  <Header />
  <main class="">
    <Hero />
    <About />
    <Features />
    <Insights />
    <Contact />
  </main>
  <Footer />
</div>

// front_end-frameworks/vue/src/App.vue
<script setup>
import Header from './components/layout/Header.vue';
import Footer from './components/layout/Footer.vue';
import Hero from './components/sections/Hero.vue';
import About from './components/sections/About.vue';
import Features from './components/sections/Features.vue';
import Insights from './components/sections/Insights.vue';
import Contact from './components/sections/Contact.vue';
</script>

<template>
  <div class="flex min-h-screen flex-col">
    <Header />
    <main class="">
      <Hero />
      <About />
      <Features />
      <Insights />
      <Contact />
    </main>
    <Footer />
  </div>
</template>
