// front_end-frameworks/vue/src/components/ui/Brand.vue
<script setup>
import { BrainCircuit } from 'lucide-vue-next';
</script>

<template>
  <a href="#top" class="flex items-center gap-2">
    <div class="flex h-7 w-7 flex-row items-center justify-center rounded-lg bg-violet-500 text-xs font-black shadow-lg shadow-violet-500/40">
      <BrainCircuit class="size-4" />
    </div>
    <span class="text-sm font-bold text-slate-50">Agentic AI</span>
  </a>
</template>

// front_end-frameworks/svelte/src/components/ui/Brand.svelte
<script>
  import { BrainCircuit } from "lucide-svelte";
</script>

<a class="flex items-center gap-2" href="#top">
  <div
    class="flex h-7 w-7 flex-row items-center justify-center rounded-lg bg-violet-500 text-xs font-black shadow-lg shadow-violet-500/40"
  >
    <BrainCircuit class="size-4" />
  </div>
  <span class="text-sm font-bold text-slate-50">Agentic AI</span>
</a>
