// front_end-frameworks/vue/src/components/ui/Highlight.vue
<script setup>
import { FolderCode, Sparkles, Users } from 'lucide-vue-next';

const props = defineProps({
  icon: {
    type: String,
    required: true
  }
});

const iconComponents = {
  FolderCode,
  Sparkles,
  Users
};

const selectedIcon = iconComponents[props.icon];
</script>

<template>
  <div class="flex gap-2">
    <component :is="selectedIcon" v-if="selectedIcon" class="m-auto size-4 stroke-violet-500" />
    <p class="text-sm text-slate-500"><slot></slot></p>
  </div>
</template>

// front_end-frameworks/svelte/src/components/ui/Highlight.svelte
<script>
  import { FolderCode, Sparkles, Users } from "lucide-svelte";

  export let icon;

  function selectIcon(icon) {
    switch (icon) {
      case "FolderCode":
        return FolderCode;
      case "Sparkles":
        return Sparkles;
      case "Users":
        return Users;
      default:
        return null;
    }
  }

  const IconComponent = selectIcon(icon);
</script>

<div class="flex gap-2">
  {#if IconComponent}
    <svelte:component this={IconComponent} class="m-auto size-4 stroke-violet-500" />
  {/if}
  <p class="text-sm text-slate-500"><slot /></p>
</div>
