// front_end-frameworks/react/src/components/Highlight.jsx
import { FolderCode, Sparkles, Users } from "lucide-react";

function selectIcon(icon) {
  switch (icon) {
    case "FolderCode":
      return <FolderCode className="m-auto size-4 stroke-violet-500" />;
    case "Sparkles":
      return <Sparkles className="m-auto size-4 stroke-violet-500" />;
    case "Users":
      return <Users className="m-auto size-4 stroke-violet-500" />;
    default:
      return null;
  }
}

export default function Highlight({ icon, children }) {
  return (
    <div className="flex gap-2">
      {selectIcon(icon)}
      <p className="text-sm text-slate-500">{children}</p>
    </div>
  );
}

// front_end-frameworks/svelte/src/components/ui/Highlight.svelte
<script>
  import { FolderCode, Sparkles, Users } from "lucide-svelte";

  export let icon;

  function selectIcon(icon) {
    switch (icon) {
      case "FolderCode":
        return FolderCode;
      case "Sparkles":
        return Sparkles;
      case "Users":
        return Users;
      default:
        return null;
    }
  }

  const IconComponent = selectIcon(icon);
</script>

<div class="flex gap-2">
  {#if IconComponent}
    <svelte:component this={IconComponent} class="m-auto size-4 stroke-violet-500" />
  {/if}
  <p class="text-sm text-slate-500"><slot /></p>
</div>
