// front_end-frameworks/svelte/src/components/ui/SectionBadge.svelte
<div
  class="mx-auto flex w-fit items-center justify-center gap-2 rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs text-violet-300"
>
  <span class="block text-[8px]">✦</span>
  <span><slot>Section Badge default text</slot></span>
  <span class="block text-[8px]">✦</span>
</div>

// front_end-frameworks/vue/src/components/ui/SectionBadge.vue
<script setup>
</script>

<template>
  <div class="mx-auto flex w-fit items-center justify-center gap-2 rounded-full border border-violet-500/20 bg-violet-500/10 px-4 py-2 text-xs text-violet-300">
    <span class="block text-[8px]">✦</span>
    <span>
      <slot />
    </span>
    <span class="block text-[8px]">✦</span>
  </div>
</template>
