// front_end-frameworks/vue/src/components/sections/Features.vue
<script setup>
import SectionBadge from '../ui/SectionBadge.vue';
import SectionTitle from '../ui/SectionTitle.vue';
import FeatureCard from '../cards/FeatureCard.vue';
import features from '../../data/features.js';
</script>

<template>
  <section
    id="features-section"
    class="flex scroll-mt-24 flex-col items-center pb-24"
  >
    <div class="mx-auto flex max-w-6xl flex-col items-center gap-8 px-6">
      <SectionBadge>Features</SectionBadge>
      <SectionTitle
        level="h2"
        text1="Everything You Need to Build"
        text2="With powerful AI agents"
      />
      <div class="mt-12 grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-3">
        <FeatureCard
          v-for="feature in features"
          :key="feature.title"
          :icon="feature.icon"
          :title="feature.title"
          :description="feature.description"
        />
      </div>
    </div>
  </section>
</template>

// front_end-frameworks/react/src/sections/Features.jsx
import Eyebrow from "../components/Eyebrow.jsx";
import FeatureCard from "../components/FeatureCard.jsx";
import features from "../data/features.js";

export default function Features() {
  return (
    <section id="features-section" className="flex flex-col items-center py-24">
      <div className="mx-auto max-w-6xl px-6">
        <Eyebrow>Features</Eyebrow>

        <h2 className="mb-24 text-center text-4xl leading-none font-black tracking-tight md:text-5xl">
          <p className="text-slate-50">Everything You Need to Build</p>
          <p className="text-violet-300">With powerful AI agents</p>
        </h2>

        <div className="grid gap-8 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
          {features.map((feature) => (
            <FeatureCard
              key={feature.title}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
