// front_end-frameworks/react/src/components/FeatureCard.jsx
import {Bot, Brain, ShieldCheck, Wrench, Database, Workflow} from 'lucide-react';

function selectIcon(icon) {
  switch(icon) {
    case 'Bot': return <Bot />;
    case 'Brain': return <Brain />;
    case 'ShieldCheck': return <ShieldCheck />;
    case 'Wrench': return <Wrench />;
    case 'Database': return <Database />;
    case 'Workflow': return <Workflow />;
    default: return null;
  }
};

export default function FeatureCard({ icon, title = "Feature Title", description = "Feature Description" }) {
  return(
    <article className="p-8 rounded-3xl border border-slate-800 bg-slate-950 shadow-xl shadow-slate-950/40">
      <div className="flex items-center justify-center size-10 mb-3 bg-violet-500 rounded-lg">
        { selectIcon(icon) }
      </div>
      <h3 className="font-bold">
        {title}
      </h3>

      <p className="text-slate-500">
        {description}
      </p>

    </article>
  );
}

// front_end-frameworks/vue/src/components/cards/FeatureCard.vue
<script setup>
import { Bot, Brain, ShieldCheck, Wrench, Database, Workflow } from 'lucide-vue-next';

const props = defineProps({
  icon: {
    type: String,
    required: true
  },
  title: {
    type: String,
    default: 'Feature Title'
  },
  description: {
    type: String,
    default: 'Feature Description'
  }
});

const iconComponents = {
  Bot,
  Brain,
  ShieldCheck,
  Wrench,
  Database,
  Workflow
};

const selectedIcon = iconComponents[props.icon];
</script>

<template>
  <article class="rounded-3xl border border-slate-800 bg-slate-950 p-8 shadow-xl shadow-slate-950/40">
    <div class="mb-5 flex size-8 items-center justify-center rounded-lg bg-violet-500 shadow-lg shadow-violet-500/40">
      <component :is="selectedIcon" v-if="selectedIcon" class="size-5" />
    </div>
    <h3 class="mb-2 font-bold">{{ title }}</h3>
    <p class="text-sm text-slate-500">{{ description }}</p>
  </article>
</template>
